# -*- coding: utf-8 -*-
"""Pandas profiling.ipynb
scikit-learn.org (all the necessary algorithm as a library)
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGrimXzDv85JPaWHXVESecu5AVfqla9L
"""
#csv file uploading facility
from google.colab import files
uploaded=files.upload()


#install ydata before use it in code otherwise it will cause error
!pip install ydata-profiling

#For Exploratory data analysis pandas profiling is used
import pandas as pd
#from pandas_profiling import ProfileReport
from ydata_profiling import ProfileReport


#fetching data from custom url
url = 'https://raw.githubusercontent.com/rashakil-ds/Public-Datasets/refs/heads/main/credit.csv'
df = pd.read_csv(url)
df.head()

#Full profiling report of analysis
profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)
profile
