# -*- coding: utf-8 -*-
"""Pandas profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGrimXzDv85JPaWHXVESecu5AVfqla9L
"""

from google.colab import files
uploaded=files.upload()

!pip install ydata-profiling

import pandas as pd
#from pandas_profiling import ProfileReport
from ydata_profiling import ProfileReport

url = 'https://raw.githubusercontent.com/rashakil-ds/Public-Datasets/refs/heads/main/credit.csv'
df = pd.read_csv(url)
df.head()

profile = ProfileReport(df, title="Pandas Profiling Report", explorative=True)
profile